#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["Examples/HelloWebApp/HelloWebApp.csproj", "Examples/HelloWebApp/"]
COPY ["SSLTerminate/SSLTerminate.csproj", "SSLTerminate/"]
COPY ["SSLTerminate.ACME/SSLTerminate.ACME.csproj", "SSLTerminate.ACME/"]
COPY ["SSLTerminate.Storage.Postgres/SSLTerminate.Storage.Postgres.csproj", "SSLTerminate.Storage.Postgres/"]
RUN dotnet restore "Examples/HelloWebApp/HelloWebApp.csproj"
COPY . .
WORKDIR "/src/Examples/HelloWebApp"
RUN dotnet build "HelloWebApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HelloWebApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HelloWebApp.dll"]