name: publish-acme-client
on: 
  push:
    branches:
      - master

env:
  PROJECT_PATH: SSLTerminate.ACME
  PACKAGE_OUTPUT_PATH: ${{ github.workspace }}/output
  NUGET_SOURCE: https://api.nuget.org/v3/index.json

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '5.0.x'
      
      - name: Build
        run:  dotnet build ${{ env.PROJECT_PATH }} --configuration=Release

      - name: Test
        run:  dotnet test

      - name: Pack
        run:  |
          dotnet pack ${{ env.PROJECT_PATH }} \
            --no-build --no-restore --configuration=Release \
            -o ${{ env.PACKAGE_OUTPUT_PATH }}

      - name: Publish
        run:  |
          dotnet nuget push ${{ env.PACKAGE_OUTPUT_PATH }}/*.* \
            --api-key=${{ secrets.NUGET_API_KEY }} \
            --source=${{ env.NUGET_SOURCE }} \
            --skip-duplicate
      
