name: publish-acme-client
on: 
  push:
    branches:
      - master

env:
  PACKAGE_OUTPUT_PATH: ${{ github.workspace }}/output
  NUGET_SOURCE: https://api.nuget.org/v3/index.json

jobs:
  build_test_and_publish:
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5435:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '5.0.x'
      
      - name: Build
        run:  dotnet build --configuration=Release

      - name: Test
        run:  dotnet test

      - name: Pack
        run:  dotnet pack --no-build --no-restore --configuration=Release -o ${{ env.PACKAGE_OUTPUT_PATH }}

      - name: Publish
        run:  |
          dotnet nuget push ${{ env.PACKAGE_OUTPUT_PATH }}/*.* \
            --api-key=${{ secrets.NUGET_API_KEY }} \
            --source=${{ env.NUGET_SOURCE }} \
            --skip-duplicate
      
